SELECT EXTRACT(MONTH FROM START_DATE) AS MONTH
     , CAR_ID
     , COUNT(HISTORY_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
   AND CAR_ID IN (
                  SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE TO_CHAR(START_DATE, 'YYYYMM') BETWEEN '202208' AND '202210'
                   GROUP BY CAR_ID HAVING COUNT(HISTORY_ID) >= 5
                 )
 GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
 ORDER BY MONTH, CAR_ID DESC;
